name: Terraform Route53 Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply for Route53
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="variables.tfvars" -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
